---
- name: Gather cluster info from given datacenter
  hosts: localhost
  connection: local
  tasks:
  - vmware_cluster_info:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      datacenter: Konsalt-MESA
      validate_certs: no
    delegate_to: localhost
    register: cluster_info
    
  - debug:
      var: cluster_info
  - debug:
      var: VMWARE_HOST VMWARE_USER
 
